application:
  port: 8000
  base_url: "http://127.0.0.1"
database:
  host: 127.0.0.1
  port: 5435
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "http://localhost"
  sender_email: "test@gmail.com"
  authorization_token: "fake-secret-token"
  timeout_ms: 10000
